### DISCUSSION TITLE
pr-mode and fetch depth

### DISCUSSION THREAD

**Discussion by ahus1** [JetBrains/Qodana#105] [Q&A] [answered]
I tested the pr-mode switch and activated it for the first time. It seems to me that checking out only the last commit is not sufficient for that in a GitHub action. I'm suspecting that I'll need to check out all commits of the PR, and probably also one more commit. 

Can you confirm what's necessary for this? I had a look [at the docs](https://www.jetbrains.com/help/qodana/qodana-jvm-docker-techs.html#Manage+plugins), and didn't find any docs about the `--commit` option. 

I'm using `JetBrains/qodana-action@v2022.1.1` and `qodana-jvm-community:2022.1`. 

Once it is known what is necessary, a minimal example for GitHub actions would be nice. For now I went with the following for PRs, some changes might be necessary when running on the main branch.

```
      - name: Fetch Sources
        # Check out current repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}
      - name: Get one more commit so Qodana we can identify the changes
        run: git fetch -q --deepen=1
```

**Comment by ahus1** [comment]
UPDATE: When running with a fetch depth of 1, I saw an error message like this. Actually it was not fatal: the analysis continued, but found no changes, therefore no violations. If it could not process an option, I'd assume it would be better for the process to fail instead of reporting everything is find. 

```
fatal: Could not parse object 'f6b17a4503cb28b1cf925f79d4f06793dbf96e8f'.
!  Could not reset git repository, no --commit option will be applied: exit status 128
```

**Reply by tiulpin** [reply]
The current implementation designed that it should not fail: there are other than GitHub default checkouts

**Reply by ahus1** [reply]
In this case, Qodana was called with `--changes --commit XXX` as parameters. If failing is not an option, I would have expected that it would analyze all files, not no files at all.

**Comment by tiulpin** [comment, marked as answer]
@ahus1 everything works as expected, you do not need to do any additional git-related operations as the action will do it all for you. All needed for this is the initial checkout with the full history, the one we are telling in the docs about. 

I could also look at the build you are trying to set up and check if everything is OK!

**Reply by ahus1** [reply]
I now found it in the docs of the GitHub action, sorry for missing it. It worked fine in a branch, and only failed on the PRs. Now I know. 

Checking out everything seems a bit too much for me, and I want to do only a minimal checkout. That's why I settled for 

```
      - name: Fetch Sources
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v3

      - name: Fetch Sources
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}

      - name: Get one more commit so Qodana we can identify the changes
        if: github.event_name == 'pull_request'
        run: git fetch --deepen=1
```

Full workflow here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/.github/workflows/docs.yml
