### DISCUSSION TITLE
Exclude not working

### DISCUSSION THREAD

**Discussion by burberius** [JetBrains/Qodana#109] [Q&A] [answered]
I try to scan a project on GitLab CI with Qodana and specified the Qodana cache into the project folder so it can be cached by GitLab CI.
But Qodana also scans the Gradle in there and finds some hundret problems.

So I tried to exclude it with, but that is not recognized! I tried relative paths, absolute and also tried to exclude some of the project files, but it was all ignored!

```
version: "1.0"
profile:
  name: qodana.recommended
exclude:
  - name: ALL
    paths:
      - qodana/cache
```

Can it be broken in the latest release? Unfortunatelly I couldn't verify it by using an old one...
