### DISCUSSION TITLE
What does the template for env look like in GitHub Actions

### DISCUSSION THREAD

**Discussion by qhy040404** [JetBrains/Qodana#118] [Q&A] [answered]
`--env ?`
I tested some data but all failed

**Comment by brichbash** [comment, marked as answer]
Hello,
It shoud look like this:
```
- name: Qodana
        uses: JetBrains/qodana-action@v2022.2.1
        with:
          args: >
            --env,FOO=BAR
```
