### DISCUSSION TITLE
qodana-python: invalid interpreter

### DISCUSSION THREAD

**Discussion by ReenigneArcher** [JetBrains/Qodana#134] [Q&A] [answered]
When using `qodana.recommended` profile, I get an `invalid interpreter` error for every file.

The same happens whether I run qodana locally (Windows) or in a github action. I do not store my `.idea` folder in github.

I attempted follow some of the suggestion here, but instead put it within the bootstrap command.
https://github.com/JetBrains/Qodana/discussions/61#discussioncomment-2059476

Latest workflow run: https://github.com/LizardByte/RetroArcher/actions/runs/3633378301

**qodana.yaml**
```yml
---
version: "1.0"
linter: jetbrains/qodana-python:2022.2-eap

bootstrap: |
  pyenv install 3.9.15
  pyenv global 3.9.15
  python3 -m venv /data/cache/venv
  source /data/cache/venv/bin/activate
  python3 -m pip install -r /data/project/requirements-dev.txt

include:
  - name: CheckDependencyLicenses

profile:
  name: qodana.recommended
```

I'd like to eventually use a profile generated from PyCharm, but first would like to get past this warning. Any ideas?
