### DISCUSSION TITLE
Why are Java inspections running in Kotlin files?

### DISCUSSION THREAD

**Discussion by skasi-surya** [JetBrains/Qodana#142] [Q&A]
We have an inspections XML profile that is passed into Qodana. This includes inspections for multiple languages - Kotlin, Java, Android, Groovy etc.

One specific inspection,  `Java -> Declaration redundancy -> Unused declaration` is showing false positives after upgrading from Qodana 2021.2 to 2022.2.

Qodana github action in workflow:

```yml
- name: Qodana Scan
    uses: JetBrains/qodana-action@v2022.2.4
    with:
      pr-mode: false
      use-annotations: true
      upload-result: false
      args: --linter,jetbrains/qodana-jvm-community:2022.2,--fail-threshold,0
```

Firstly, why are Java inspections running on Kt files? Also, as seen in the screenshot, it is clearly a false positive as the parameters are being used.

`qodana.yml` and `Inspections.xml` have been included in the zip for reference.

![image](https://user-images.githubusercontent.com/78728234/206963882-d3dd16d4-d18f-4019-9c86-44f7730ff4d1.png)

[Inspections.zip](https://github.com/JetBrains/Qodana/files/10204784/Inspections.zip)

**Comment by brichbash** [comment]
Hello,

Could you please try using the `jetbrains/qodana-jvm-community:2022.3` linter? I couldn't reproduce the issue in version 2022.3. In 2022.2 there are indeed these false positive "Unused Declaration" problems.

**Reply by skasi-surya** [reply]
Have tried with `jetbrains/qodana-jvm-community:2022.3` , same issue persists.

Github Action:

```yaml
- name: Qodana Scan
  uses: JetBrains/qodana-action@v2022.3.0
  with:
    pr-mode: false
    use-annotations: true
    upload-result: false
    args: --linter,jetbrains/qodana-jvm-community:2022.3,--fail-threshold,0
```
