### DISCUSSION TITLE
[Github] Qodana action fails againt pull request

### DISCUSSION THREAD

**Discussion by imedbha** [JetBrains/Qodana#148] [Q&A] [answered]
I try to run Qodana againt pull request on our github repository, but got stuck with this error:

` SEVERE - #c.i.o.e.i.ExtensionPointImpl - Cannot invoke "javax.swing.JRootPane.registerKeyboardAction(java.awt.event.ActionListener, javax.swing.KeyStroke, int)" because the return value of "com.intellij.openapi.fileEditor.impl.NonProjectFileWritingAccessDialog.getRootPane()" is null`

And then:
`WARN - #c.j.r.p.VfsToProjectModelEvents - Unable to modify solution or project, some operation is already in progress., reason: JetBrains.DocumentManagers.Transactions.ProjectModelEditorException: Unable to modify solution or project, some operation is already in progress.`

Github action workflow is configured with thid code_quality.yml :
```
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
```
