### DISCUSSION TITLE
How To Specify "project dir" on Qodana Scan for Azure Pipelines?

### DISCUSSION THREAD

**Discussion by lfaltran** [JetBrains/Qodana#170] [Q&A] [answered]
Hello, I'm trying to use "--project-dir" flag on my task: QodanaScan@2023 with "args" (as bellow), but, the process fail with error:

```
✓  Finished pulling the latest version of linter
/azp/_work/_tool/qodana/2023.1.0/x64/qodana scan --skip-pull --cache-dir /azp/_work/_temp/qodana/cache --results-dir /azp/_work/_temp/qodana/results --project-dir /azp/_work/8/_source_branch

Error: unknown flag: --project-dir /azp/_work/8/_source_branch
Usage:
  qodana scan [flags]

Flags:
  -l, --linter string             Override linter to use
  -i, --project-dir string        Root directory of the inspected project (default ".")
  -o, --results-dir string        Override directory to save Qodana inspection results to (default <userCacheDir>/JetBrains/<linter>/results)
      --cache-dir string          Override cache directory (default <userCacheDir>/JetBrains/<linter>/cache)
  -e, --env stringArray           Define additional environment variables for the Qodana container (you can use the flag multiple times). CLI is not reading full host environment variables and does not pass it to the Qodana container for security reasons
  -v, --volume stringArray        Define additional volumes for the Qodana container (you can use the flag multiple times)
```

My task
```
      - task: QodanaScan@2023
        displayName: "Qodana - Run"
        inputs:
          args: '--project-dir $(PR_SOURCES_DIRECTORY)'
          cacheDir: $(QODANA_CACHE_DIR)
          resultsDir: $(QODANA_RESULTS_DIR)
```
