### DISCUSSION TITLE
How can I include Python "PyPep8Inspection" but only exclude its E501 warning

### DISCUSSION THREAD

**Discussion by MKPlato** [JetBrains/Qodana#173] [Q&A]
I just started Qodana yesterday, so my Qodana profile is still very simple ,  I actually want to include PyPep8Inspection except one code style E501 - line width must less than 80 characters.  How can I do this? 

```
version: "1.0"
profile:
  name: qodana.starter
exclude:
  - name: PyPep8Inspection
```
