### DISCUSSION TITLE
How to exclude target paths using an existing IntelliJ IDEA inspection profile

### DISCUSSION THREAD

**Discussion by Tereo725** [JetBrains/Qodana#175] [Q&A] [answered]
Hey,

i know it's possible to exclude paths with a qodana.yml like this:
version: "1.0"
exclude:
  - name: All
    paths:
      - relative/path/to/your/file.kt
 
And it's possible to add a custom profile to exclude all target folder like this: 
name: "Excluded target folders"
baseProfile: qodana.recommended
inspections:
  - group: ALL
    ignore:
      - "scope#file:**/target//*"

Is there a way to use the IntelliJ IDEA inspection profile instead of a qodana.yml or custom profile as a ruleset and exclude specific file path and e.g. all target folder?

**Comment by brichbash** [comment]
Hi,

You can use your IDEA profile and set the required scope in a yaml profile that extends your profile.
For that, your IDEA xml profile should be stored under your project root in `.idea/inspectionProfiles/`, and you should create a `yaml` profile with the following content:
```
name: "Excluded target folders"
baseProfile: <your-idea-profile-name>
inspections:
  - group: ALL
    ignore:
      - "scope#file:**/target//*"
      - <scope-2>
```
You could also avoid using the yaml profile by creating [a shared scope in IntelliJ IDEA ](https://www.jetbrains.com/help/idea/settings-scopes.html), [setting the scope](https://www.jetbrains.com/help/idea/inspections-settings.html#5) for required inspections in your profile and then keeping the generated files under `.idea/scopes` & `.idea/inspectionProfiles` in your repository. After that, you can [apply ](https://www.jetbrains.com/help/qodana/inspection-profiles.html#Profile+name) this profile in Qodana.

**Reply by Tereo725** [reply]
I created a xml profile `My_Ruleset.xml` via IntelliJ, and stored it under my project root in `.idea/inspectionProfiles/` and i created a `profile.yaml` with the following content:
```
name: "Excluded target folders"
baseProfile: My_Ruleset
inspections:
  - group: ALL
    ignore:
      - "scope#file:**/target//*"
```

Do i still need a qodana.yaml if i want to use it locally via docker or via CI/CD in our gitlab repo?
With our previous ruleset, we used a qodana.yaml with all inspection and exlude rules in it and a CI/CD-Step with a script like this:
`qodana --save-report --results-dir=$CI_PROJECT_DIR/qodana --report-dir=$CI_PROJECT_DIR/qodana/report --property=idea.log.config.file=debug.xml --fail-threshold 5`

Do i have to change my CI/CD steps for qodana? Where do i have to refere to the profile.yaml? Or does this part stay the same and I write in the Qodana.yaml something like this:
```
profile:
  path: relative/path/in/your/project/profile.yaml
```
