### DISCUSSION TITLE
Manage monorepo with multiple languages

### DISCUSSION THREAD

**Discussion by tretail** [JetBrains/Qodana#182] [Ideas]
Hello there!

Unless I missed something, it seems rather difficult to manage monorepo with multiple languages and setup Qodana:
- Qodana configuration file (qodana.yml) must be at root
- A Qodana file/project handles a single language through the linter property

Suppose the following project:
```
|- .github/workflows/qodana-action.yml # use the Github Qodana Action
|- client-side/ # JS-relative languages
|- server-side/ # JVM-relative languages
|- qodana.yml # must be at root, will set a single linter (js or jvm)
```

There is today no clean solution.

Two possible solutions:
- Set a qodana-js.yml and a qodana-jvm.yml and use it from the Github Qodana Action. Those files should be recognized by IDE too. ([More or less the same discussion here](https://github.com/JetBrains/Qodana/discussions/153))
- Be able to set multiple linters in a configuration files, and filter language into the Qodana Cloud project interface.

I believe the first option is by far the simplest.

**EDIT**
Just read about [--project-dir argument](https://www.jetbrains.com/help/qodana/docker-image-configuration.html#docker-config-reference-directories) that we may use with Github Action (example below). Nevertheless, IDE integration is not so good, and this doesn't answer the question if multiple languages share the same root.

```yaml
      - name: 'Qodana Scan JS'
        with:
          args: --project-dir,client-side
        uses: JetBrains/qodana-action@latest
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_JS }}
```
