### DISCUSSION TITLE
Bitbucket pipelines support

### DISCUSSION THREAD

**Discussion by KevinVG** [JetBrains/Qodana#193] [Q&A]
Hello,

Is there support to integrate bitbucket pipelines and Qodana?

**Comment by gabrielrbarbosa** [comment]
👀

**Comment by brichbash** [comment]
Hello,

There is no official extension for Bitbucket similar to what we have for [GitHub Actions](https://github.com/marketplace/actions/qodana-scan) or [Azure DevOps](https://marketplace.visualstudio.com/items?itemName=JetBrains.qodana). However, you can still run Qodana in your pipelines because we distribute Qodana as Docker images. Here is an example of Qodana configuration on Bitbucket:
```
image: atlassian/default-image:4

pipelines:
  branches: 
   main:
      - step:
          name: Qodana
          caches:
           - qodana
          image: jetbrains/qodana-jvm
          script:
            - export QODANA_TOKEN=$QODANA_TOKEN
            - qodana --results-dir=$BITBUCKET_CLONE_DIR/.qodana --report-dir=$BITBUCKET_CLONE_DIR/.qodana/report --cache-dir=$BITBUCKET_CLONE_DIR/.qodana/cache --save-report
          artifacts:
          - .qodana/report

definitions:
  caches:
    qodana: .qodana/cache
```
`$QODANA_TOKEN` from the example is[ a secured environment variable ](https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/#Secured-variables) containing a [Qodana Cloud](https://www.jetbrains.com/help/qodana/cloud-about.html) token required for using Qodana.

Let me know if you have any questions.
