### DISCUSSION TITLE
Disable `Expression statement is not assignment or call` on Javascript unit tests

### DISCUSSION THREAD

**Discussion by luislobo** [JetBrains/Qodana#198] [Q&A]
It is not uncommon to use the following "non-normal" production code javascript expressions on unit tests.

```javascript
foundDashboard.groups.should.be.an('array').that.is.not.empty;
```

How can I disable that check on all my unit tests folder?

**Comment by brichbash** [comment]
Hello,
You can exclude the inspection from your tests directory by adding to `qodana.yaml` in your project root: 
```
exclude:
  - name: BadExpressionStatementJS
    paths:
      - path/to/tests/dir
```
