### DISCUSSION TITLE
Azure Pipelines - Ubuntu trying to run the wrong version of dotnet

### DISCUSSION THREAD

**Discussion by ChaseFlorell** [JetBrains/Qodana#207] [Q&A] [answered]
I'm not sure if this is the right place to ask, but I'm going to try.
I'm running into an issue whereby I've got my Azure pipeline yml file configured to use the correct version of .NET (8.0.100) as described in my global.json, but when I run Qodana in CI, it keeps erroring, stating that it can only find .NET 6. Can anyone help direct me to what I might be missing?

<img width="1121" alt="image" src="https://github.com/JetBrains/Qodana/assets/471626/c05a46a2-db88-40f8-807f-14d3505b961b">

my yml is pretty straight forward

```yml

stages:
  - stage: ubuntu_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Run
        displayName: 'Code Analysis'
        dependsOn: [  ]
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 8'
            inputs:
              packageType: sdk
              version: 8.0.100
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - task: Cache@2  # Not required, but Qodana will open projects with cache faster.
            inputs:
              key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
              path: '$(Agent.TempDirectory)/qodana/cache'
              restoreKeys: |
                "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
                "$(Build.Repository.Name)"
          - task: QodanaScan@2023
            env:
              QODANA_TOKEN: $(QODANA_TOKEN)
```
