### DISCUSSION TITLE
The .NET 8 support comes with Qodana 2023.3-eap

### DISCUSSION THREAD

**Discussion by smth-to-smb** [JetBrains/Qodana#211] [Announcements]
If you migrated to a new version of the .NET framework, you might be having some issues with scanning projects using the **Qodana for .NET** linter. 

Starting from version 2023.3-eap, Qodana supports .NET 8, and we plan to officially release the linter before the end of the year. 
In the meantime, we'd like to help you make the most of code quality with Qodana so you will need to migrate if you haven't done it already. 

For example, if you are using the Qodana Scan GitHub action in your GitHub pipelines, you can use the following pipeline configuration:

```yaml
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --linter,jetbrains/qodana-dotnet:2023.3-eap # Specify the 2023.2-eap version of Qodana for .NET linter
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
```

In case of Azure Pipelines, you can use the following configuration sample:

```yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Cache@2
    inputs:
      key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
      path: '$(Agent.TempDirectory)/qodana/cache'
      restoreKeys: |
        "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
        "$(Build.Repository.Name)"
  - task: QodanaScan@2023
    env:
      QODANA_TOKEN: $(QODANA_TOKEN)
    # Specify the 2023.2-eap version of Qodana for .NET linter
    inputs:
      args: '--linter,jetbrains/qodana-dotnet:2023.3-eap'
```

For the CI/CD systems that employ the Docker images of Qodana, you can specify the `jetbrains/qodana-dotnet:2023.3-eap` linter
as described [here](https://www.jetbrains.com/help/qodana/ci.html). For example, for a Jenkins Pipeline you can use the following configuration: 

```yaml
pipeline {
    environment {
        QODANA_TOKEN=credentials('qodana-token')
    }
    agent {
        docker {
            args '''
              -v "${WORKSPACE}":/data/project
              --entrypoint=""
              '''
            image 'jetbrains/qodana-dotnet:2023.3-eap'
        }
    }
    stages {
        stage('Qodana') {
            steps {
                sh '''qodana'''
            }
        }
    }
}
```
