### DISCUSSION TITLE
A single Qodana scan summary comment for a monorepo

### DISCUSSION THREAD

**Discussion by simoami** [JetBrains/Qodana#221] [Q&A]
We have a monorepo with multiple subprojects hosted in github. The GH actions is setup to scan various subfolders. However, the scan summary results that appear as a comment in the PR override each other. I can confirm this by looking as the comment edit history to see that the various reports were posted and replaced in the same sequence that the scan jobs completed. 

Option 1: Is there a way to give the scan comments separate ids to allow them to appear separately 
Option 2: Is there a way to aggregate all the subproject scan reports into a single comment
Option 3: This is more of a complementary behavior,  but is there a way to skip a scan from running and producing a report and comment when there are no commits in the subproject path?

My GH actions
```
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - versions/2.2.0
      - "release-*"

jobs:
  qodana-backend-api:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install dependencies
        run: yarn --cwd backend/api install

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2023.3
        with:
          push-fixes: pull-request
          args: |
            --source-directory,backend/api,
            --baseline,qodana-backend-api.sarif.json
          artifact-name: qodana-backend-api
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_BACKEND_API_TOKEN }}

  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --cwd frontend install

      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2023.3
        with:
          push-fixes: pull-request
          args: |
            --source-directory,frontend,
            --baseline,qodana-frontend.sarif.json
          artifact-name: qodana-frontend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
```

Image shows that there was a report by the backend api scan and was later replaced by the frontend scan which did not have any related changes:
<img width="1031" alt="Screenshot 2024-01-26 at 6 10 19 PM" src="https://github.com/JetBrains/Qodana/assets/2038264/30110aa7-d36b-43e3-a27a-e1e719ab9857">
