### DISCUSSION TITLE
CI/CD + Docker: How do you pass arguments to the scan command?

### DISCUSSION THREAD

**Discussion by josephtaylor** [JetBrains/Qodana#234] [Q&A]
When invoking the qodana scan from CI/CD and docker, curious what the preferred strategy is for setting any of the command-line arguments to the command. For example things like: `--profile-name`,  `--profile-path`, `--env`.

**Comment by josephtaylor** [comment]
My bad. Staring me right in the face here. In the configuration there's the `script` block which defines the command:
```yaml
qodana:
   image:
      name: jetbrains/qodana-<linter>
   ...
   script:
      - qodana <all your args go here>
   ...
```
