### DISCUSSION TITLE
QodanaScan@2023 task from Qodana extension for Azure Pipelines: Cannot locate baseline report file

### DISCUSSION THREAD

**Discussion by agthring** [JetBrains/Qodana#239] [Q&A]
Hi,
I have Qodana running in an Azure Pipeline with the following YAML config:

```yaml
      - job: Qodana
        displayName: Qodana scan
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Cache@2  # Not required, but Qodana will open projects with cache faster.
            inputs:
              key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
              path: '$(Agent.TempDirectory)/qodana/cache'
              restoreKeys: |
                "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
                "$(Build.Repository.Name)"
          - script: 'ls -la $(Build.Repository.LocalPath)'
            displayName: "ls -la the Build.Repository.LocalPath"
          - task: QodanaScan@2023
            inputs:
              args: '-l,jetbrains/qodana-dotnet:latest,--baseline,$(Build.Repository.LocalPath)/qodana-baseline.sarif.json'
            env:
              QODANA_TOKEN: $(QODANA_TOKEN)
```

The `'ls -la $(Build.Repository.LocalPath)` script I added does list my baseline file in the root of my repo:

```
ls -la /home/vsts/work/1/s
... other files and directories ...
-rw-r--r--  1 vsts docker 7054780 Feb 28 14:27 qodana-baseline.sarif.json
```

However, the QodanaScan task complains

```
Can't find baseline report file: /home/vsts/work/1/s/qodana-baseline.sarif.json. Baseline will be calculated against empty report.
```

Anyone know what I'm doing wrong?
