### DISCUSSION TITLE
A branch was not detected by qodana linter

### DISCUSSION THREAD

**Discussion by ghisleouf** [JetBrains/Qodana#249] [Q&A]
Hello Qodana community,

I'm new in Qodana magic world and trying to setup the tool in our Gitlab CI.
I can now generate reports and send them to Qodana Cloud ... but, currently, when running a Qodana job, it actually cannot detect that we are on the develop branch.

My qodana job is performed on every merge request events on gitlab ci:
```
.rules_quality:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.quality_common:
  stage: quality
  image:
    name: jetbrains/qodana-js
    entrypoint: [""]
  variables:
    QODANA_TOKEN: $QODANA_PROJECT_TOKEN
  cache:
    - key: qodana-2023.3-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2023.3-$CI_DEFAULT_BRANCH-
        - qodana-2023.3-
      paths:
        - .qodana/cache
  script:
    - qodana  --save-report --results-dir=$CI_PROJECT_DIR/.qodana/results --cache-dir=$CI_PROJECT_DIR/.qodana/cache --baseline=$CI_PROJECT_DIR/qodana.sarif.json
  artifacts:
    paths:
      - .qodana/results/
    expose_as: 'Qodana report'

# keep it separated regarding possible upcoming changes
quality_merge_request:
  extends:
   - .quality_common
   - .rules_quality
 ```

And here is what I can see on Qodana UI:
![image](https://github.com/JetBrains/Qodana/assets/1439092/f342d3eb-ef71-4411-bd8c-f7d108d33902)

Do you have any idea why it cannot detect the related branch ?

Thanks for your help.

Best regards :)
