### DISCUSSION TITLE
Qodana github action when gradle project is in sub folder

### DISCUSSION THREAD

**Discussion by Ironeer** [JetBrains/Qodana#250] [Q&A]
Hey Qodana community,

I  am new to Qodana and try to get it to generate the same .java inspections in a github action as my IntelliJ IDEA(2024.1 Ultimate).
Unfortunately I am not able to get any inspections on .java files with the github actions. There it only finds mistakes in .md, .xml, .json and even .ts despite using qodana-jvm. When I run the Server-Side Analysis in IntelliJ IDEA .java file mistakes are found.

Can you please help me?

My repository structure:
* .git
* lsp-server
  * src
     * lsp
       * *.java files
  * qodana.yaml (used locally, but only the relative path is different from the qodana.yaml in root folder and used by github action)
* qodana.yaml

My github workflow yaml:
```yaml
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
```

My qodana.yaml
```yaml
version: "1.0"

projectJDK: 19
linter: jetbrains/qodana-jvm:2023.3
profile:
  path: lsp-server/.idea/inspectionProfiles/Project_Default.xml
```
