### DISCUSSION TITLE
Exclude with patterns option not working

### DISCUSSION THREAD

**Discussion by codingcircus** [JetBrains/Qodana#259] [Q&A] [answered]
Hello. i'm trying currently to configure qodana for my js app to exclude all spec files. According to [the documentation](https://www.jetbrains.com/help/qodana/qodana-yaml.html#exclude-paths) this should be possible via the patterns argument, however this is not working for me. Even more, I checked the schema for qodana and it also does not mention the patterns option, so the only reference for this is in this documentation. 

Can anybody confirm that I'm going about this the right way? This is my full yaml file: 

```
version: "1.0"
linter: jetbrains/qodana-js:2024.1
profile:
  name: qodana.recommended
exclude:
  - name: All
    patterns:
      - "**/*.spec.*"

```

**Comment by brichbash** [comment, marked as answer]
Hello,

It's known issue. Please as an alternative try using [yaml profiles](https://www.jetbrains.com/help/qodana/custom-profiles.html).
1. create a yaml file under `.qodana/`, e.g. `.qodana/my-profile.yaml`
The content of the yaml profile:
```
name: "Ignore spec files"

baseProfile: qodana.recommended # It should use your profile stored under .idea/inspectionProfiles
inspections:
  - group: "ALL"
    ignore:
      - "**/*.spec.*"
```
2. in your `qodana.yaml` set the profile path to `.qodana/my-profile.yaml` instead of `qodana.recommended`:
```
profile:
  path: .qodana/my-profile.yaml
```
