### DISCUSSION TITLE
Can the Qodana tool be used with JDK 1.8 adopt version?

### DISCUSSION THREAD

**Discussion by Woodo-VIRNECT** [JetBrains/Qodana#260] [Q&A] [answered]
Hello Qodana Team~ 
I am trying to use your Qodana tool for static analysis in the CI process by leveraging Git Actions. 

like this :
```
name: Develop Branch Push

on:
  push:
    branches:
      - develop

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx2g -XX:MaxMetaspaceSize=512m' -Dorg.gradle.parallel=true"
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Set executable permission for Gradle Wrapper
        run: chmod +x ./gradlew
        working-directory: ./

      - name: Validate Gradle Wrapper version
        run: ./gradlew --version
        working-directory: ./

      - name: Create code coverage folder if not exists
        run: |
          mkdir -p .qodana/code-coverage
        working-directory: ./

      - name: Set executable permission for Gradle Wrapper
        run: chmod +x gradlew
        working-directory: ./

      - name: Run tests and Jacoco
        run: |
          ./gradlew test jacocoTestReport
        working-directory: ./

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data-jacoco
          path: .qodana/code-coverage

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
          cache-dir: .qodana/cache
          results-dir: .qodana/results
``` 

However, I encountered the following error. It seems that you are using JDK 17 internally
![스크린샷 2024-08-29 오전 10 12 25](https://github.com/user-attachments/assets/4dadddc2-acc1-47ea-b901-52c0d53979a1)

does this mean that it cannot be used with JDK 1.8? 
How can I fix this?

**Comment by brichbash** [comment, marked as answer]
Hello,

Please try adding to `qodana.yaml` in your project root:
```
projectJDK: 1.8
```

**Reply by Woodo-VIRNECT** [reply]
@brichbash 
Hello, thanks for your advice. 🙇‍♀️
Now, I'm trying it like this, and it's working correctly.
Could you take a look at the code below and let me know if you have any further suggestions?

```shell
version: "1.0"
profile:
  name: qodana.starter
projectJDK: corretto-1.8
fixesStrategy: cleanup
include:
  - name: CommentedOutCode
  - name: Deprecation
  - name: JavadocDeclaration
  - name: NonFinalFieldInEnum
  - name: UnnecessarySemicolon
  - name: UnnecessaryToStringCall
  - name: UNUSED_IMPORT
  - name: FieldMayBeFinal
  - name: DefaultAnnotationParam
  - name: StringEqualsEmptyString
  - name: NullableProblems
  - name: LombokGetterMayBeUsed
  - name: LombokSetterMayBeUsed
  - name: RedundantTypeArguments
  - name: ParameterNamingConvention
  - name: MethodNamingConvention
  - name: ClassNamingConvention
  - name: CatchException
  - name: DataClass
  - name: NonStrictComparisonCanBeEquality
linter: jetbrains/qodana-jvm:2024.1
```

**Reply by brichbash** [reply]
The setup looks ok. It all depends on your needs so it's difficult for me to recommend to you anything. You can check [Inspectopedia](https://www.jetbrains.com/help/inspectopedia/WhatIsNewInspections.html) to search for different inspections what you might need. At the bottom of each page you'll find whether this inspection is available in Qodana and what [plugin](https://www.jetbrains.com/help/qodana/extending-qodana-plugins.html#extending-qodana-repository-plugins-configure-plugin) provides it.

**Reply by Woodo-VIRNECT** [reply]
@brichbash 

Thanks for your answer! 
I'm sorry, but could I ask you just one more thing?
I'm using Gradle and Cache to build in the CI pipeline, and I want to speed up the build process.(now is 7mimutes)
Is there any way to improve the build speed?

Below is my GitHub Actions configuration.
```
name: Develop Branch Push

on:
  push:
    branches:
      - develop

concurrency:
  group: "develop-branch"
  cancel-in-progress: false

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.jvmargs='-Xmx2g -XX:MaxMetaspaceSize=512m' -Dorg.gradle.parallel=true"
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties', '**/settings.gradle*', '**/build.gradle*') }}-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Validate JAVA_HOME
        run: echo $JAVA_HOME

      - name: Set executable permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper version
        run: ./gradlew --version

      - name: Run tests and Jacoco
        run: ./gradlew test jacocoTestReport

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: gradle-coverage-data-jacoco
          path: .qodana/code-coverage

  analyze:
    name: Run Qodana Analysis
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          name: gradle-coverage-data-jacoco
          path: .qodana/code-coverage

      - name: Cache Qodana
        uses: actions/cache@v4
        with:
          path: .qodana/cache
          key: ${{ runner.os }}-qodana-${{ hashFiles('**/*.java') }}
          restore-keys: |
            ${{ runner.os }}-qodana-

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false
          cache-dir: .qodana/cache
          results-dir: .qodana/results
```
