### DISCUSSION TITLE
Qodana Analysis Github Action Seems to not Recognize the Baseline

### DISCUSSION THREAD

**Discussion by wbcrawford** [JetBrains/Qodana#279] [Q&A]
We are trying to pilot Jetbrains Qodana, I seem to have the Github Action running and generating reports on my PR and it appears to be working fine.

But, I have added exclusion lists to my qodana.yaml file and a baseline file with many other issues that my codebase is generating but every time I initiate a PR into the branch, it looks like it is ignoring the baseline and exclusions and returning 7,000+ errors in my code. I do not have the Qodana config files merged into the main develop branch. They are in my test branch and I want to get this into a manageable state before merging into develop.

I have a mono-repo where my backend C# code is in the server/ directory.

I am not seeing any errors in the output log related to the baseline file.

We are currently using the Community edition for Qodana.

## Github Action:
```
name: Code Quality Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      test-branch
jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Backend'
        uses: JetBrains/qodana-action@v2024.3
        with:
          upload-result: true
          args: |
            --project-dir,server,--linter,jetbrains/qodana-cdnet:2024.3-eap,--baseline,baseline/qodana.sarif.json
          artifact-name: qodona-backend
          cache-default-branch-only: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
```

## Qodana Yaml:
```
version: "1.0"
linter: jetbrains/qodana-cdnet:2024.3-eap
dotnet:
  solution: server.sln
#Specify inspection profile for code analysis
profile:
  name: qodana.recommended
exclude:
  - [EXCLUDED FOR BREVITY]
  - name: All
    paths:
      - [EXCLUDED FOR BREVITY]
```
