### DISCUSSION TITLE
I configured spellchecking in my repository with Grazie and Qodana

### DISCUSSION THREAD

**Discussion by tiulpin** [JetBrains/Qodana#49] [Show and tell]
What if Qodana could inspect not only source code files? Actually, it can!

- Installed Grazie Professional plugin (https://plugins.jetbrains.com/plugin/16136-grazie-professional)
- Enabled the new checks from the plugin, which are
  - name: `GrazieInspection`
  - name: `IdentifierGrammar`
  - name: `LanguageDetectionInspection`
- Prepared the whole Qodana workflow:

```yaml
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  qodana:
    runs-on: ubuntu-latest
    env:
      GRAZIE_PLUGIN: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=152587
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -L -o grazie-pro.zip "$GRAZIE_PLUGIN" && unzip grazie-pro.zip
          cat > qodana.yaml << EOF  # too lazy to put qodana.yaml to my repo now, so creating it on the go
          profile:
            name: empty
          include:
            - name: GrazieInspection
            - name: IdentifierGrammar
            - name: LanguageDetectionInspection
          exclude:
            - name: All
              paths:
                - .github
          EOF
      - name: 'Qodana for Docs (with Grazie)'
        uses: JetBrains/qodana-action@main
        with:
          linter: jetbrains/qodana-js:latest
          use-annotations: false
          additional-volumes: |
            ${{ github.workspace }}/grazie-pro:/opt/idea/plugins/grazie-pro
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
```

🎉 So, it works, and I can see the found problems right on GitHub

<img width="971" alt="CleanShot 2022-01-20 at 17 36 56@2x" src="https://user-images.githubusercontent.com/13538286/150359418-da85dfb3-92b9-4ffd-867e-a32ee25c97a9.png">
