### DISCUSSION TITLE
Exclude generated code from analysis

### DISCUSSION THREAD

**Discussion by cardosojc** [JetBrains/Qodana#56] [Q&A] [answered]
Hi,
I'm using dagger (DI library) in my project and in the report there are a lot of errors about the generated code from this library. Is there a way to exclude it from the analysis ?

**Comment by tiulpin** [comment, marked as answer]
Is this code located in some known directory?
You can exclude it with qodana.yaml — https://www.jetbrains.com/help/qodana/qodana-yaml.html#exclude-paths

```yaml
exclude:
  - name: All
    paths:
      - asm-test/src/main/java/org
      - asm/Visitor.java
      - benchmarks
```

**Update:** run the code generation step before the Qodana analysis starts. If you added the directories/files to `qodana.yaml` correctly, this way it should be excluded for sure.
