### ISSUE TITLE
qodana.yaml file isn't read and load

### ISSUE THREAD

**Issue by LocalHeroPro** [JetBrains/Qodana#14]
Steps to reproduce:
1. Create `qodana.yaml` file in the same folder where you point docer - for me it's `-v /var/www/site.local/html/`:
```yaml
version: 1.0
failThreshold: 0
profile:
  name: qodana.site
exclude:
  - name: All
    paths:
      - public
      - storage
      - vendor

```
2. Run docker:
```bash
docker run --rm -it -v /var/www/site.local/html/:/data/project/ -p 8080:8080 jetbrains/qodana --show-report
```
I get 
```bash
// ...
Starting up IntelliJ IDEA 2020.3.2 (build IJCA-203.6906) ...done.
Opening project...done.
Initializing project...Loaded profile 'qodana.recommended' from file '/data/profile.xml'
Inspecting with profile 'qodana.recommended'
Analyzing code 0%
// ...
```
So I can't see that my custom `qodana.yaml` file is imported ;/
Also, can I check in the browser what settings are imported? Or or what name of profile is imported?
